AllCops:
  Exclude:
    - 'bin/*'
    - 'config/*'
    - 'config/*/*'
    - 'coverage/*'
    - 'db/*'
    - 'db/*/*'
    - 'lib/*'
    - 'log/*'
    - 'public/*'
    - 'test/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'tmp/*'
    - 'vendor/*'
    - 'app/assets/*'
    - 'app/channels/*'
    - 'app/controllers/*'
    - 'app/helpers/*'
    - 'app/jobs/*'
    - 'app/mailers/*'
    - 'app/views/*'
    - 'Rakefile'
    - 'Gemfile'