# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 033e362bef9c590cafc38444abdec31c69eaed2df5f2e982024e4aee7c71b98291055cafbb64eb06751dae3f30ae874b8a011c8405932287affe01f4e18c69f1

test:
  secret_key_base: 49008d5a8454b117e5bc9abd0ca10b66cc33ecb87f67756ca4b4c2fd128f042b80ebadcabe4171424ffdc454d79b6575e1688f61deb066e968f354ede75f5d9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
